### ISSUE TITLE
No module named 'gehomesdk'

### ISSUE THREAD

**Issue by kevchu3** [simbaja/ha_gehome#315]
I have loaded this ha_gehome repository in my custom_components folder, and am running HA 2024.11.3 in Kubernetes.  I've been running this for years, and have intermittently come across this issue when trying to reinstantiate my device integration: `Config flow could not be loaded: {"message":"Invalid handler specified"}`

I have always just restarted the pod per https://github.com/simbaja/ha_gehome/issues/282 to resolve the issue.  However, this doesn't appear to address the issue anymore, I'm not sure what has changed.  Here's a look at my HA pod log, and I've confirmed this error is logged when I encounter the error above during integration:
```
2024-12-06 15:03:01.770 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration ge_home: No module named 'gehomesdk'
```

**Comment by mhoran** [comment]
I believe this is a Home Assistant issue. I ran into this as well and came across https://github.com/home-assistant/core/issues/127966. Setting `PYTHONPATH=/config/deps` as suggested seems to work for me (for now…)

**Comment by simbaja** [comment]
Seems like this is resolved, feel free to comment if not and I'll reopen.

**Comment by jlaska** [comment]
Still getting this error when attempting to install on 2024.12.5. The integration fails to install from the front-end with the following error

```
Error
Config flow could not be loaded: {"message":"Invalid handler specified"}
```

the home-assistant log shows the following 

```
Error occurred loading flow for integration ge_home: No module named 'gehomesdk'
```

**Comment by jlaska** [comment]
Working now!  For others who might be hitting this ... I uninstalled the HACS component, updated to 2025.1.0, reinstalled HACS component via custom repository, installed the GE Home integration successfully.  Thank you for this work!

**Comment by kevchu3** [comment]
I've confirmed that this now works for me as well - I updated to HA 2025.1.2 and pulled the latest code from this repo.  Thank you for resolving this!
