### ISSUE TITLE
Feature Request: Add Energy Usage Data

### ISSUE THREAD

**Issue by dylanpjones** [simbaja/ha_gehome#335]
I would like to be able to see energy usage data on my GE washer / dryer so I can import into the home assistant energy monitor.

**Comment by simbaja** [comment]
Might be possible, can you run the debug library from the [SDK](https://github.com/simbaja/gehome) and post logs?  I don't know which ERD codes are used for your appliance, but we can see if they can be spotted in the logs.

**Comment by digital-grease** [comment]
Came here to ask for this feature as well.

**Comment by dylanpjones** [comment]
> Might be possible, can you run the debug library from the [SDK](https://github.com/simbaja/gehome) and post logs? I don't know which ERD codes are used for your appliance, but we can see if they can be spotted in the logs.

Sorry for my delayed response here! Is there instructions somewhere on how to run the SDK and get this info? I can do this with a bit of coaching / instruction.

**Comment by paulgoodjohn** [comment]
> > Might be possible, can you run the debug library from the [SDK](https://github.com/simbaja/gehome) and post logs? I don't know which ERD codes are used for your appliance, but we can see if they can be spotted in the logs.
> 
> Sorry for my delayed response here! Is there instructions somewhere on how to run the SDK and get this info? I can do this with a bit of coaching / instruction.

The ERD you're looking for is 0xd030 (this is an example for water heaters but it should be common across all appliances):
https://github.com/geappliances/home-assistant-examples/blob/9b8edf7e5eae21a9f10faf7ad17bbd4f53722202/packages/waterheater.yaml#L670

**Comment by GeekNathan** [comment]
I have a Haier heat pump hot water unit (reports into Smart HQ, don't ask me why) . Would love to get power (in W) feeding into my power data along with everything else.

**Comment by jth-67** [comment]
I’m new at this. Is running the debug library involve adding something to the configuration.yaml?

**Comment by chrisolson91** [comment]
Just wanted to add that I'd love to see this as well. If I can help in any way let me know! I primarily interested in my dishwasher energy usage

**Comment by DigitalCharon** [comment]
I updated to 2026.6.0 but don't see any energy usage entities on my water heater.

**Comment by simbaja** [comment]
Looks like water heaters are "special" and don't use the common energy codes.  I'll have to take a look and work through it for those.

**Comment by paulgoodjohn** [comment]
> Looks like water heaters are "special" and don't use the common energy codes. I'll have to take a look and work through it for those.

The current water heaters support the common energy used 0xD030 ERD, as well as 0x4072 estimated power consumption....however the 0x4072 isn't available from SmartHq, only by direct connection.

**Comment by simbaja** [comment]
I've only implemented ERD 0xd005-0xd021 as part of resource monitoring, I'll have to look at the 0xd030 as well it seems.

**Comment by mz1234567890** [comment]
Edit: I was able to set up a [utility meter](https://www.home-assistant.io/integrations/utility_meter/) helper to track the usage for the energy dashboard, I don't think a code change is needed, but perhaps a piece of documentation. I had the "net consumption" setting off, "delta values" on, "periodically resetting" on, "sensor always available" off. I'm leaving the original comment as a quote for reference.

> It looks like the data that is being reported as cumulative energy usage isn't actually cumulative, at least for my fridge. It looks like the reported value is reset each hour, rather than always increasing.
> 
> In the energy dashboard it ends up not super useful as it's expecting it to be total increasing.
> 
> <img width="552" height="406" alt="Image" src="https://github.com/user-attachments/assets/971828eb-ef7f-4d0b-aaa3-ff02f6f680fd" />
> 
> I can open a separate issue if that would be your preferred approach.

**Comment by jscooksey** [comment]
I'm on v2026.6.0 and have a Fisher & Paykel Dishwasher connected. 23 entites, all seem to be working as expected (Tested under previous version).

I now have the entity **resource_dsm_power_usage_instantaneous_power_w** so measuring Watts.  I haven't had a cycle done yet, to test out return values.  I don't have a cumulative power entity appearing (yet?) so I cant add to the power dashboard.
But awesome that we can get power measurements now thank you.

I'll report in after I done the next cycle and and advise what I get, if any issues.

**Comment by jscooksey** [comment]
OK, I'm not getting any data on Power entity, but others are working fine.  So I can see the dishwasher start and run through its operation.

<img width="578" height="787" alt="Image" src="https://github.com/user-attachments/assets/d2022772-201f-4b76-80be-52c5506ab9b3" />

But over that same period, Power does not change at all. However, even in the SmartHQ app I'm not sure I get power usage.
I will see if I can integrate the API directly as some have, and see what it does have available.

<img width="1648" height="477" alt="Image" src="https://github.com/user-attachments/assets/adc279e6-3256-4982-99c4-38367f6e2d91" />

**Comment by simbaja** [comment]
I'm going to close this out, I think I've implemented what I can.  If something else is identified, please let me know.

**Comment by DigitalCharon** [comment]
Umm, my water heater still doesnt have energy metrics. Is there something I can do to help?

**Comment by simbaja** [comment]
If the official app has energy metrics, it should be possible somehow.  If it doesn't, I'm doubtful.  If it does, it's using a different ERD code than the standard ones I've found and implemented, so it would need to be something specific for that device.  I'd suggest opening a different issue for just your water heater if the official app shows it.  In that issue, provide your debug logs and maybe the correct ERD can be found.  It also might not be possible in the v1 API this integration uses, you might want to check the new official integration: https://github.com/geappliances/geappliances-smarthq-integration

**Comment by paulgoodjohn** [comment]
> Umm, my water heater still doesnt have energy metrics. Is there something I can do to help?

What model water heater is it? The energy metrics were added in the development of the latest water heater models, all the older models don't have the ability to measure the energy usage.

**Comment by DigitalCharon** [comment]
> > Umm, my water heater still doesnt have energy metrics. Is there something I can do to help?
> 
> What model water heater is it? The energy metrics were added in the development of the latest water heater models, all the older models don't have the ability to measure the energy usage.

Its a PH50S10BNY01. Fairly new water heater. In the app, it shows this for energy usage: 

<img width="1080" height="2520" alt="Image" src="https://github.com/user-attachments/assets/ada9e7e5-2981-4e0f-bda4-62ce5b808966" />

**Comment by paulgoodjohn** [comment]
OK, yes that should implement `Erd_EnergyUsedWattHours, 0xD030`

The only reason that might not be present is if the software in it is pretty old - have you updated to the latest released code?

**Comment by DigitalCharon** [comment]
Yes. Its on 45.0.16.098

<img width="1080" height="2520" alt="Image" src="https://github.com/user-attachments/assets/c88984b2-9036-43d5-9f12-de2bcc694749" />

**Comment by paulgoodjohn** [comment]
That's the same SW version as mine - it definitely should have 0xD030.
