### ISSUE TITLE
Integration fails to set up

### ISSUE THREAD

**Issue by giraldojc** [simbaja/ha_gehome#411]
After downloading the integration and restarting HA, I launch the SmartHQ integration and I get the following error:
"Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

How can I get past this issue?

Thank you.

**Comment by simbaja** [comment]
I've published a new pre-release version that may help (see #423), let me know if it does.

**Comment by adayalMD** [comment]
Same error still occurring on v2025.11.0-dev2
Home Assistant Details: 

Installation method
Home Assistant OS
Core
2025.11.3
Supervisor
2025.11.4
Operating System
16.3
Frontend
20251105.1

Device: Raspberry Pi 5

Logger: aiohttp.server
Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:481
First occurred: 12:45:00 PM (1 occurrence)
Last logged: 12:45:00 PM

Error handling request from fe80::1448:a317:9bc6:17d3
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 87, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 83, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 188, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 195, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 83, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1464, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1502, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1724, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.hass, handler_key, self._hass_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3990, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3967, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 584, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
        hass, integration.domain
    )
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await future
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
    await self.async_process_requirements(
        integration.domain, integration.requirements
    )
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 264, in async_process_requirements
    self._raise_for_failed_requirements(name, missing)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 292, in _raise_for_failed_requirements
    raise RequirementsNotFound(integration, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for ge_home not found: ['gehomesdk==2025.11.5'].

**Comment by adayalMD** [comment]
How would I run the pip command on a Home Assistant OS installation on a RPi 5?

**Comment by simbaja** [comment]
From a quick search (no idea if it works):

**Advanced/Temporary Methods (Not Recommended for Permanent Use)**
If you need pip for temporary debugging or testing and understand the risks, you can access the Home Assistant Core container's shell and run pip commands there. These changes will be lost after a Home Assistant update or reboot. 
- Enable SSH access via the Terminal & SSH add-on (or a direct console connection to the Raspberry Pi).
- Log in as root at the prompt.
- Type login again at the ha > prompt to access the host shell.
- Enter the Home Assistant container using a command like: docker exec -it homeassistant /bin/bash.
- Run your pip command inside the container shell (e.g., pip install your-package-name). 

Did a restart not work?  Others seem to be able to test the latest version, and the library is definitely out in Pypi, so HA should be able to find it.

**Comment by adayalMD** [comment]
Now I got another error message: 

Logger: homeassistant.util.package
Source: util/package.py:159
First occurred: 7:10:19 PM (6 occurrences)
Last logged: 7:10:41 PM

Unable to install package gehomesdk==2025.11.5: error: Failed to fetch: `https://files.pythonhosted.org/packages/28/1e/f0e9b101aa6eb4de98e80b75c7080d1618f18f623aebfb51c6a8b7914c4b/gehomesdk-2025.11.5-py3-none-any.whl.metadata` Caused by: Request failed after 3 retries Caused by: error sending request for url (https://files.pythonhosted.org/packages/28/1e/f0e9b101aa6eb4de98e80b75c7080d1618f18f623aebfb51c6a8b7914c4b/gehomesdk-2025.11.5-py3-none-any.whl.metadata) Caused by: client error (Connect) Caused by: dns error Caused by: failed to lookup address information: Name does not resolve
Unable to install package magicattr==0.1.6: error: Failed to fetch: `https://files.pythonhosted.org/packages/2a/7e/76b7e0c391bee7e9273725c29c8fe41c4df62a215ce58aa8e3518baee0bb/magicattr-0.1.6-py2.py3-none-any.whl.metadata` Caused by: Request failed after 3 retries Caused by: error sending request for url (https://files.pythonhosted.org/packages/2a/7e/76b7e0c391bee7e9273725c29c8fe41c4df62a215ce58aa8e3518baee0bb/magicattr-0.1.6-py2.py3-none-any.whl.metadata) Caused by: client error (Connect) Caused by: dns error Caused by: failed to lookup address information: Name does not resolve

**Comment by simbaja** [comment]
That appears to be a DNS issue, it can't resolve the server name.  Do you run PiHole or anything?  If so, perhaps check in there for something blocked.

**Comment by adayalMD** [comment]
Fixed It! I disabled iPv6 and changed DNS to 1.1.1.1. Worked

**Comment by simbaja** [comment]
Closing now that 2025.11.0 has been released, please let me know if issues still persist.
